Reorganize
h4570/tyra pull request #118
Opened 2022-07-19 00:33 UTC by wolfysdl

2022-07-19 06:50 UTC, h4570 commented
That is a surprise!
Thank you for your contribution!

2022-07-19 14:00 UTC, wolfysdl commented
> That is a surprise! Thank you for your contribution!
> 
> Please check out the ROADMAP.TXT file from `tyrav2-develop` branch We discussed about putting `2020-2022` everywhere, but it can be `2022` everywhere also.

It will maintained 2020-2022 however newer files should be only 2022

2022-07-19 14:07 UTC, h4570 requested changes
Small mistakes

2022-07-19 14:07 UTC, h4570 commented on engine/inc/audio/audio.hpp
> +# Wellinaton Carvalho <wellcoj@gmail.com>
Typo, please fix all of `Wellinaton` typos via CTRL+F

2022-07-19 14:07 UTC, h4570 commented on engine/inc/loaders/texture/png_loader.hpp
> +# Copyright 2022, tyra - https://github.com/h4570/tyra
Hmm I dont get it.
We should be consistent with this
`2022` or `2020-2022` (the same for other places)

2022-07-19 14:07 UTC, h4570 commented on engine/inc/loaders/3d/builder/mesh_builder_material_data.hpp
> +# Copyright 22020 - 2022022, tyra - https://github.com/h4570/tyra
Typo

2022-07-19 14:07 UTC, h4570 commented on ROADMAP.txt
> +- [General] All Copyrights to 2020-2022 and add clang format check(Codacy)
Cool idea!

2022-07-19 14:07 UTC, h4570 commented on engine/inc/debug/debug.hpp
> +# Copyright 2020 - 2022, tyra - https://github.com/h4570/tyra
Could you include #117 for these changes?

2022-07-19 14:11 UTC, h4570 commented
> > That is a surprise! Thank you for your contribution!
> > Please check out the ROADMAP.TXT file from `tyrav2-develop` branch We discussed about putting `2020-2022` everywhere, but it can be `2022` everywhere also.
> 
> It will maintained 2020-2022 however newer files should be only 2022

So how about putting 2022 everywhere? I like to be this simple and same in every place.

2022-07-19 14:13 UTC, Wolf3s commented on engine/inc/debug/debug.hpp
> +# Copyright 2020 - 2022, tyra - https://github.com/h4570/tyra
Sure

2022-07-31 09:56 UTC, h4570 commented
Due to inactivity - I fixed it by myself

2022-07-31 09:56 UTC, closed without merging

2022-07-31 11:51 UTC, wolfysdl commented
> Due to inactivity - I fixed it by myself

Yeah but i stopped becuase of the merge and patience