Support hdd loading modules
h4570/tyra pull request #141
Opened 2022-08-31 09:17 UTC by wolfysdl

2022-08-31 09:25 UTC, h4570 requested changes

2022-08-31 09:25 UTC, h4570 commented on demo/inc/game_settings.hpp
>  # Copyright 2022, tyra - https://github.com/h4570/tyra
I have better idea.
Please remove this your new variable and rename `IS_REAL_PS2_VIA_USB` to `IS_REAL_PS2_VIA_EXT_DEV`
and just load both, USB driver and HDD driver.

You can add `HDD support` to `README`

2022-08-31 09:25 UTC, h4570 commented on engine/src/irx/irx_loader.cpp
> +extern u8 ps2hdd_irx[];
Could you show any proof that Tyra sample works on real PS2 hardware via HDD?

2022-08-31 09:25 UTC, h4570 commented on engine/src/irx/irx_loader.cpp
> +void IrxLoader::loadAll(const bool& withUsb, const bool &withHdd,const bool& isLoggingToFile) {
Lint problem, please fix all format errors - codacy check failed

2022-08-31 09:25 UTC, h4570 commented on engine/src/irx/irx_loader.cpp
> +  else if (withHdd) {
I believe that there should be `if` instead of `else if`

2022-08-31 09:52 UTC, wolfysdl commented on engine/src/irx/irx_loader.cpp
> +void IrxLoader::loadAll(const bool& withUsb, const bool &withHdd,const bool& isLoggingToFile) {
Solver but i need to fix the other one that makes the codacy yelling.

2022-08-31 09:57 UTC, wolfysdl commented on engine/src/irx/irx_loader.cpp
> +extern u8 ps2hdd_irx[];
I found one but no images

2022-08-31 10:04 UTC, h4570 commented on engine/src/irx/irx_loader.cpp
> +extern u8 ps2hdd_irx[];
We must be sure that is working, and it not broked USB loading.

2022-08-31 10:38 UTC, wolfysdl commented on engine/src/irx/irx_loader.cpp
> +  else if (withHdd) {
Well in my form this one should be use 
like this to select better but i'm not descarting the other method

2022-08-31 10:49 UTC, wolfysdl commented on engine/src/irx/irx_loader.cpp
> +extern u8 ps2hdd_irx[];
> We must be sure that is working, and it not broked USB loading.

I Found a tester

2022-08-31 10:54 UTC, h4570 commented on engine/src/irx/irx_loader.cpp
> +  else if (withHdd) {
I didnt get it.
With current code, it is impossible to load USB and HDD at the same time.

2022-08-31 11:41 UTC, wolfysdl commented on engine/src/irx/irx_loader.cpp
> +  else if (withHdd) {
You are right probablly this one should be load both even if it says else if, i should change soon

2022-08-31 11:42 UTC, wolfysdl commented on demo/inc/game_settings.hpp
>  # Copyright 2022, tyra - https://github.com/h4570/tyra
Excelent

2022-08-31 18:14 UTC, wolfysdl commented on engine/src/irx/irx_loader.cpp
> +extern u8 ps2hdd_irx[];
So i can have some proofs

2022-09-04 13:24 UTC, h4570 commented
Wassup Wolfy.
Any plan to continue this PR?
Should I close it?

2022-09-04 13:35 UTC, wolfysdl commented
> Wassup Wolfy. Any plan to continue this PR? Should I close it?

Well i think noy, but the loading module needs to be fixed the hdd support should be probally ok.

2023-02-01 12:25 UTC, h4570 commented
Closing due to inactivity.

2023-02-01 12:25 UTC, closed without merging

2023-02-01 12:30 UTC, wolfysdl commented
> Closing due to inactivity.

Perfect... but the last time i was updating the drivers with the ps2_drivers by matta you should check out.